### ISSUE TITLE
g_convert() problems

### ISSUE THREAD

**Issue by Andy2244** [sergey-senozhatsky/cifsd-tools2#1]
Ok i will keep this issue in here, mail is really bad at formatting text.

I found the problem:
```
iconv -l
ANSI_X3.4-1968 ANSI_X3.4-1986 ASCII CP367 IBM367 ISO-IR-6 ISO646-US ISO_646.IRV:1991 US US-ASCII CSASCII
UTF-8
ISO-10646-UCS-2 UCS-2 CSUNICODE
UCS-2BE UNICODE-1-1 UNICODEBIG CSUNICODE11
UCS-2LE UNICODELITTLE
ISO-10646-UCS-4 UCS-4 CSUCS4
UCS-4BE
UCS-4LE
UTF-16
UTF-16BE
UTF-16LE
UTF-32
UTF-32BE
UTF-32LE
UNICODE-1-1-UTF-7 UTF-7 CSUNICODE11UTF7
UCS-2-INTERNAL
UCS-2-SWAPPED
UCS-4-INTERNAL
UCS-4-SWAPPED
CP819 IBM819 ISO-8859-1 ISO-IR-100 ISO8859-1 ISO_8859-1 ISO_8859-1:1987 L1 LATIN1 CSISOLATIN1
ISO-8859-2 ISO-IR-101 ISO8859-2 ISO_8859-2 ISO_8859-2:1987 L2 LATIN2 CSISOLATIN2
ISO-8859-15 ISO-IR-203 ISO8859-15 ISO_8859-15 ISO_8859-15:1998 LATIN-9
KOI8-R CSKOI8R
CP1250 MS-EE WINDOWS-1250
437 CP437 IBM437 CSPC8CODEPAGE437
```
Compare:
```
char *cifsd_conv_charsets[CIFSD_CHARSET_MAX + 1] = {
	"UTF8",
	"UTF16LE",
	"UCS-2LE",
	"UTF16BE",
	"UCS-2BE",
	"OOPS"
};
```
vs 
```
UTF-8
UTF-16BE
UTF-16LE
```

After adding the missing "-" the cifsadmin -a worked, except this small error.
```
cifsadmin -a andy5
New password:
Retype new password:
[cifsdadmin/21393]: DEBUG: Unalde to read lock file: No such file or directory
[cifsdadmin/21393]: DEBUG: Kill user andy5
```
The database file was created correctly, yet some call tries to use the lock file?

**Comment by Andy2244** [comment]
Ah and i still get the same error for cifsd:
```
cifsd -n
[cifsd-worker/21420]: ERROR: Recv() error No error information
[cifsd-worker/21420]: DEBUG: Kill share ipc$
[cifsd-worker/21420]: DEBUG: Kill user andy5
```

Will try to setup more debug options and figure out what call fails.

**Comment by sergey-senozhatsky** [comment]
Thanks, Andy!

I'll add more alt names.

On my x86 box:

iconv -l | tr -d ',//' | wc -l
1179

...
       UCS-4LE, UCS2, UCS4, UHC, UJIS, UK, UNICODE, UNICODEBIG, UNICODELITTLE,
       US-ASCII, US, UTF-7, UTF-8, UTF-16, UTF-16BE, UTF-16LE, UTF-32, UTF-32BE,
       UTF-32LE, UTF7, UTF8, UTF16, UTF16BE, UTF16LE, UTF32, UTF32BE, UTF32LE,
....


> [cifsdadmin/21393]: DEBUG: Unalde to read lock file: No such file or directory
> [cifsdadmin/21393]: DEBUG: Kill user andy5

This is one not a problem, I'll drop that pr_debug() maybe.
cifsadmin sends a SIGHUP signal to cifsd, if it can find out cifsd's PID (from cifsd's PID file).

-ss

**Comment by sergey-senozhatsky** [comment]
> cifsd -n
> [cifsd-worker/21420]: ERROR: Recv() error No error information
> [cifsd-worker/21420]: DEBUG: Kill share ipc$
> [cifsd-worker/21420]: DEBUG: Kill user andy5
> ```


Hmm, that one comes from libnl

>         if (nl_recvmsgs_default(sk) < 0) {                                      
>                pr_err("Recv() error %s\n", strerror(errno));                   
>                 return -EINVAL;                                                 
>         }                                                                       

-ss

**Comment by Andy2244** [comment]
ok closing this, seems g_convert() now works.
```
cifsadmin -a andy
New password:
Retype new password:
[cifsdadmin/10434]: DEBUG: Kill user andy
```
The last line debug message should be changed to something that gives feedback that the user was successfully added to the database file and if the file did not exists, it should be noted where the files was created.

I will open a separate issue on the main repo for the libnl problem. Will try to grab some more error codes on this one.

**Comment by sergey-senozhatsky** [comment]
> ok closing this, seems g_convert() now works.

Thanks. I kept it "opened" because you mentioned two problems and we don't have any
solution to the second one yet.

> The last line debug message should be changed to something that gives feedback
> that the user was successfully added to the database file

OK.

> and if the file did not exists, it should be noted where the file was created.

Can do. Not sure if this is information is valuable tho.

-ss
